### ISSUE TITLE
Missing assets: GitHub Pages not displaying properly

### ISSUE THREAD

**Issue by plbstl** [plbstl/icon-previewer#1]
This repo is  deployed simultaneously to GitHub Pages and Netlify.

It displays correctly on Netlify. See https://6489cd17207ee90009819190--aip1.netlify.app/.

But deployments to GitHub Pages using actions (currently in beta) doesn't display correctly.

I have viewed the action logs and skimmed through the source code for [actions/upload-pages-artifact](https://github.com/actions/upload-pages-artifact), [upload-artifact](https://github.com/actions/upload-artifact), and [@actions/artifact](https://github.com/actions/toolkit/tree/main/packages/artifact). All seems well. I'm yet to look into [actions/deploy-pages](https://github.com/actions/deploy-pages) and the outputted URLs in the action logs.

### Screenshots

<details>
  <summary> &nbsp; Elements tab in dev tools</summary>
  <br />
  <img width="645" alt="Elements tab in Edge dev tools" src="https://github.com/plbstl/icon-previewer/assets/49006567/8a2d1a58-0695-48eb-94a4-63e80f592bfa">
</details>

<details>
  <summary> &nbsp; Network tab in dev tools</summary>
  <br />
  <img width="647" alt="Network tab in Edge dev tools" src="https://github.com/plbstl/icon-previewer/assets/49006567/727573b7-e496-4b1b-8e29-3663fbeb31e3">
</details>

### Response headers

The response headers differ from other deployed pages projects. Here, I am comparing my main CSS file with `base.css` from "square.github.io". Note that this can be a CSS file from any proper working deployed project.

| - | plbstl.github.io/icon-previewer | square.github.io |
| --- | :---: | :---: |
| access-control-allow-origin | ❌ | * |
| age | 872 (higher than others) | 4 (sometimes as low as zero) |
| cache-control | ❌  | max-age=600 |
| content-security-policy | default-src 'none'; style-src 'unsafe-inline'; img-src data:; connect-src 'self' | ❌ |
| content-type | text/html; charset=utf-8 (requested a CSS file!) | text/css; charset=utf-8 |
| expires | ❌  | approximately 10 mins after `Date` header |
| last-modified | ❌ | `Datetime` |

### Conclusion

The assets are obviously not there, that's why GitHub sends a generic 404 HTML. Maybe they're in another location, who knows. I am not done debugging but that's taking some time. I'll switch to classic GitHub Pages on the `main` branch with a `/docs` folder. This is very okay for my current setup.

---
Edit: I really needed that sleep 🤦‍♂️

The problem is the link tag href attribute. It starts with an absolute path of `/` instead of `/icon-previewer/`.

As per `http://username.github.io/repository`.

See: https://pages.github.com

**Comment by plbstl** [comment]
gh-pages with a specified branch uses actions under the hood 🤦‍♂️
using netlify for now

**Comment by SP321** [comment]
https://github.com/plbstl/icon-previewer/pull/3
this should fix the issue.

**Comment by plbstl** [comment]
Yes it should. Thank you
